# Minimal local stubs for pyrage (native module, ships no type
# information — ty cannot introspect pyrage.abi3.so). Only the surface
# the worker uses is typed; extend as needed.
from collections.abc import Sequence

from pyrage import x25519 as x25519

class EncryptError(Exception): ...
class DecryptError(Exception): ...
class IdentityError(Exception): ...
class RecipientError(Exception): ...

def encrypt(plaintext: bytes, recipients: Sequence[object]) -> bytes: ...
def decrypt(ciphertext: bytes, identities: Sequence[object]) -> bytes: ...
def encrypt_file(infile: str, outfile: str, recipients: Sequence[object]) -> None: ...
def decrypt_file(infile: str, outfile: str, identities: Sequence[object]) -> None: ...
