class Recipient:
    @staticmethod
    def from_str(s: str) -> Recipient: ...
    def __str__(self) -> str: ...

class Identity:
    @staticmethod
    def generate() -> Identity: ...
    @staticmethod
    def from_str(s: str) -> Identity: ...
    def to_public(self) -> Recipient: ...
    def __str__(self) -> str: ...
